Added code as suggested. Loking forward on how to test
amezin/gnome-shell-extension-ddterm pull request #30
Opened 2021-04-02 14:17 UTC by henrj

2021-04-02 17:07 UTC, amezin requested changes
I think you missed the step "connect the shortcut to the action".

2021-04-02 17:07 UTC, amezin commented on appwindow.js
> +            this.unmaximize_action = this.simple_action('unmaximize', () => this.unmaximize());
Why do you need a dedicated `unmaximize`?

2021-04-02 17:07 UTC, amezin commented on application.js
> +            this.add_action(this.window.toggle_unmaximize_action);
This copies `win.*` actions to `app.*`. Shouldn't be necessary.

2021-04-02 17:07 UTC, amezin commented on application.js
> +            this.add_action(this.window.toggle_unmaximize_action);
If I'm not mistaken, this is necessary only for actions that you want to work globally - i. e. when terminal window isn't active. IMO it's not needed for maximize/unmaximize

2021-04-02 17:07 UTC, amezin commented on glade/prefs.ui
> +        <col id="1" translatable="yes">Toggle Terminal Window Max Size</col>
Maybe "Maximize/Unmaximize Terminal Window"?

2021-04-02 17:09 UTC, amezin commented
For testing look at https://github.com/amezin/gnome-shell-extension-ddterm/blob/master/docs/INSTALL.md#install-from-git-repository
Just skip the first step (`git clone`)

2021-04-03 05:23 UTC, amezin commented
Hm. Actually, the extension tries to unmaximize the window when it's maximized: https://github.com/amezin/gnome-shell-extension-ddterm/blob/master/extension.js#L285 This is because GNOME's window manager tries to auto-maximize the window sometimes (when it covers more than 80% of the screen work area). So you'll have to modify the extension too. I would add `maximize-window` to the settings schema [after `window-height`](https://github.com/amezin/gnome-shell-extension-ddterm/blob/master/schemas/com.github.amezin.ddterm.gschema.xml#L72), change its value from the app, and modify the extension to react to it/take it into account when resizing the window.

2021-04-03 09:32 UTC, henrj commented
> For testing look at https://github.com/amezin/gnome-shell-extension-ddterm/blob/master/docs/INSTALL.md#install-from-git-repository
> Just skip the first step (`git clone`)

The extension does not open (Fedora 34)

Tried looking in the log with:
`journalctl /usr/bin/gnome-shell -f -o cat`
Nothing related to ddterm there.

No error logged in looking glass either (`Alt + F2 -> lg -> Enter`)

Thanks

2021-04-08 07:04 UTC, amezin commented
1) There is an issue in application code (`journalctl --user -f`):
```
апр 08 13:01:05 trx40 gjs[21139]: JS ERROR: Error: Expected an object of type GAction for argument 'action' but got type undefined
                                     startup@/home/amezin/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/application.js:108:18
                                     @/home/amezin/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/application.js:233:5
```

2021-04-09 14:06 UTC, henrj commented
Thanks @amezin, did not think in looking for it there `journalctl --user -f`

I'll look into it tomorrow.

2021-04-13 16:03 UTC, scarlehoff commented
I'm very much interested in this feature as well. Let me know if you need more hands for testing (using arch + gnome40)

2021-04-25 12:21 UTC, amezin commented
@henrj Do you still plan to work on this?

2021-05-13 07:11 UTC, amezin commented
Superseded by https://github.com/amezin/gnome-shell-extension-ddterm/pull/40

2021-05-13 07:11 UTC, closed without merging